---
output:
  word_document: default
  html_document: default
---
```{r}
#install.packages("AER")
library(AER)
data(SportsCards)
data <- SportsCards
head(data)
```



```{r}
set.seed(2380)
data_splitted <- sample(nrow(data), nrow(data) * 0.8) #Spliting data into two parts
training_data <- data[data_splitted,]
testing_data  <- data[-data_splitted,]
nrow(training_data);nrow(testing_data)
summary(SportsCards$trade)
```
```{r}
model <- glm(trade ~.,data = training_data, family = "binomial") 
summary(model)
```


```{r}
predicted_probs_train <- predict(model,type = "response")
predicted_class_train <- ifelse(predicted_probs_train > 0.5, "yes", "no")
mean(predicted_class_train == training_data$trade)
```
```{r}
predicted_probs_test <- predict(model,testing_data,type = "response")
predicted_class_test <- ifelse(predicted_probs_test > 0.5, "yes", "no")
mean(predicted_class_test == testing_data$trade)
```

```{r}
table(predicted=predicted_class_test,actual=testing_data$trade)
```

